export const OULU_STORES = [
  { id: "k-market-asemantorni", name: "Asemantorni - K-Market" },
  { id: "k-market-etu-lyotty", name: "Etu-Lyötty - K-Market" },
  { id: "k-market-haapalehto", name: "Haapalehto - K-Market" },
  { id: "k-supermarket-hiukkavaara", name: "Hiukkavaara - K-Supermarket" },
  { id: "k-market-honttamaki", name: "Hönttämäki - K-Market" },
  { id: "k-market-iikka", name: "Iikka - K-Market" },
  { id: "k-supermarket-joutsensilta", name: "Joutsensilta - K-Supermarket" },
  { id: "k-citymarket-oulu-kaakkuri", name: "Kaakkuri - K-Citymarket" },
  { id: "k-supermarket-kaijonharju", name: "Kaijonharju - K-Supermarket" },
  { id: "k-market-karjasilta", name: "Karjasilta - K-Market" },
  { id: "k-market-kastelli", name: "Kastelli - K-Market" },
  {
    id: "k-supermarket-knuutilankangas",
    name: "Knuutilankangas - K-Supermarket",
  },
  { id: "k-market-koskela", name: "Koskela - K-Market" },
  { id: "k-market-kuivasjarvi", name: "Kuivasjärvi - K-Market" },
  { id: "k-market-linnanherkku", name: "LinnanHerkku - K-Market" },
  { id: "k-market-metsokangas", name: "Metsokangas - K-Market" },
  { id: "k-market-myllyoja", name: "Myllyoja - K-Market" },
  { id: "k-market-myllytulli", name: "Myllytulli - K-Market" },
  { id: "k-market-pateniemenranta", name: "Pateniemenranta - K-Market" },
  { id: "k-supermarket-pekuri", name: "Pekuri - K-Supermarket" },
  { id: "k-market-pyykosjarvi", name: "Pyykösjärvi - K-Market" },
  { id: "k-citymarket-oulu-raksila", name: "Raksila - K-Citymarket" },
  { id: "k-supermarket-ritaharju", name: "Ritaharju - K-Supermarket" },
  { id: "k-market-ruokavinkki-oulu", name: "Ruokavinkki - K-Market" },
  { id: "k-citymarket-oulu-rusko", name: "Rusko - K-Citymarket" },
  { id: "k-supermarket-toppila", name: "Toppila - K-Supermarket" },
  { id: "k-market-torinranta", name: "Torinranta - K-Market" },
  { id: "k-market-tuira", name: "Tuira - K-Market" },
  { id: "k-market-valjaspuisto", name: "Valjaspuisto - K-Market" },
  { id: "k-supermarket-valivainio", name: "Välivainio - K-Supermarket" },
  { id: "k-market-vartto", name: "Värttö - K-Market" },
];
